<?php if (isset($this->view->errors)): ?>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <?php foreach ($this->view->errors as $msg): ?>
            <p><?php echo $msg?></p>
        <?php endforeach;?>
    </div>
<?php endif; ?>