<?php if (isset($this->view->success)): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
    <?php foreach ($this->view->success as $msg): ?>
        <p><?php echo $msg?></p>
        <?php endforeach;?>
    </div>
<?php endif; ?>