<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/assets/css/style.css">

    <title><?php  $this->getPageTitle("|") ?>Browork</title>
</head>
<body>
<?php  require_once  __DIR__. "/menu.phtml"?>
<?php $this->content() ?>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="/assets/js/jquery.min.js" ></script>
<script src="/assets/js/popper.min.js" ></script>
<script src="/assets/js/bootstrap.min.js" ></script>
</body>
</html>



